server {
    listen 80;
    server_name _;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    # CSP для Keycloak iframe (для будущей фичи SSO)
    add_header Content-Security-Policy "frame-ancestors 'self' http://localhost:8080 https://localhost:8080;" always;

    # SPA routing — всё на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэш для статики
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
